# Generated by Django 5.0.3 on 2024-03-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=20)),
                ('recipe_desc', models.CharField(max_length=200)),
                ('recipe_ingredients', models.CharField(max_length=200)),
                ('recipe_instructions', models.CharField(max_length=500)),
                ('recipe_date', models.DateTimeField()),
            ],
        ),
    ]
